#pragma once


#define DEBUGGING_DEVICE_LOST false
#define USING_NVIDIA_AFTERMATH false && DEBUGGING_DEVICE_LOST

#define GPU_LOGGING true
#define DECONSTRUCTION_DEBUG true

#define DEBUGGING_PIPELINES false
#define DEBUGGING_DYNAMIC_PIPE false